name: Continuous Integration
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v2
      - name: Install Packages
        run: make install
      - name: Format
        run: make format
      - name: Train
        run: make training-set
      - name: Evaluation
        env:
          REPO_TOKEN: ${{ secrets.GB_TOKEN }}
        run: make eval
      - name: Ashhar Branch
        env:
          NAME: ${{ secrets.USER_NAME }}
          EMAIL: ${{ secrets.USER_EMAIL }}
        run: make ashhar-branch USER_NAME=$NAME USER_EMAIL=$EMAIL
